# Generated by Django 3.0.4 on 2020-03-27 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200327_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecobag',
            name='left',
            field=models.IntegerField(default=0, verbose_name='How much bags left in stock?'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='company',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Company name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Получен', max_length=150),
        ),
    ]
