# Generated by Django 3.0.4 on 2020-03-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_goods'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecobag',
            name='has_lock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ecobag',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
